[package]
name = "actix_derive"
version = "0.1.1"
authors = ["Callym <hi@callym.com>", "Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actor framework for Rust"
readme = "README.md"
keywords = ["actor", "futures", "actix", "async", "tokio"]
homepage = "https://github.com/actix/actix-derive/"
repository = "https://github.com/actix/actix-derive.git"
documentation = "https://docs.rs/actix-derive/"
categories = ["network-programming", "asynchronous"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
build = "build.rs"

[lib]
proc-macro = true

[dependencies]
quote = "0.4"
rand = "0.3"
syn = { version = "0.12.5", features = ["full", "extra-traits"] }
proc-macro2 = { version = "0.2", features = ["nightly"] }

[build-dependencies]
version_check = "0.1"
