[package]
name = "actix_derive"
version = "0.0.1"
authors = ["Callym <hi@callym.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.3.15"
syn = "0.11.11"

[dev-dependencies]
actix = "0.3.2"
futures = "0.1"